### ISSUE TITLE
Upgrading to Podman 4.5 broke... lots

### ISSUE THREAD

**Issue by deboer-tim** [podman-desktop/podman-desktop#2338]
### Bug description

Podman was originally installed via brew, so I used the recommended `brew update && brew upgrade podman` to upgrade.

After this, I could not restart the main podman machine I was using before. I could start others, but no containers showed up and all of my machines now show as started or stopped at the same time.

I created a new machine, and could start and stop it ok (but still all other machines have the same status). I could not pull an image from Podman Desktop or via cli, until I did a `podman system connection default new45`.

I can now pull images from the cli, but still not from within Podman Desktop. The error is `Could not connect to Podman Machine new45: No provider with a running engine`.

From within the UI can I create a container from the image, but I cannot create pods: `Error: No provider with a running engine`.

### Operating system

macOS 13.3 M1

### Version

next (development version)

**Comment by deboer-tim** [comment]
I deleted all machines, created a new one, and still had the same problem. Minutes later, it has all resolved itself except for all machines showing the same started/stopped status. I'd really like to know what was going on, but monitoring things for now.

**Comment by odockal** [comment]
@deboer-tim I am facing similar problems, or I have the feeling to be precise, since I am trying not to reproduce, but rather test other scenarios. 
In summary, right now on Windows with Podman desktop 0.15.0 using podman 4.5.0.
I am facing these problems:
* (Image pull) `Could not connect to Podman Machine: No provider with a running engine` happend when I start podman desktop and initialized and start podman machine or when I change system connection, I need to totally restart PD.
* I do not see actual image pulled, container or pod created on the particular pages unless I do manually `CTRL + R`
* Settings->Resources->Podman machine restart hangs endlessly, If I change page and get back, it seems to be stopped (but is actually running) I need to start it which is fails (since it is started). Again, `CTRL+R` solve the problem.
